export const routes = {
  versions: {
    v1: "/v1",
    v2: "/v2",
    v3: "/v3",
  },
  student: {
    _id: "/Api/students",
    login: "/login",
    getInfo: "/get/information",
    createStudent: "/create/student",
    updateStudent: "/update/student",
    deleteStudent: "/delete/student",
    searchByInstudent: "/search/for/students",
    AddImgByAdmin: "/Add/image/to/student/by/Admin",
    AddImgByStu: "/Add/image/to/student/by/student",
    deleteImgByAdmin: "/delete/image/from/student/By/Admin",
    deleteImgBystu: "/delete/image/from/student/By/student",
    Availablecourses: "/get/available/courses",
  },
  Admin: {
    _id: "/Api/admins",
    login: "/login",
    getinfo: "/get/info",
    createAdmin: "/create/admin",
    updateAdmin: "/update/admin",
    deleteAdmin: "/delete/admin",
    searchAdmin: "/search/admin",
    AddImgBySuper: "/add/image/to/admin/by/super",
    AddImgByAdmin: "/add/image/to/admin/by/admin",
    deleteImgBysuper: "/delete/image/from/admin/by/super",
    deleteImgByAdmin: "/delete/image/from/admin/by/admin",
    dashboardAdmin: "/information",
  },
  instructor: {
    _id: "/Api/instructors",
    createInstructor: "/create/instructor",
    updateInstructor: "/update/instructor",
    deleteInstructor: "/delete/instructor",
    searchInstructor: "/search/instructor",
    AddImgByInstructor: "/Add/image/to/instructor/By/instructor",
    AddImgByAdmin: "/Add/image/to/instructor/ByAdmin",
    deleteImgByInstructor: "/delete/image/to/instructor/by/instructor",
    deleteImgByAdmin: "/delete/image/to/instructor/by/Admin",
  },
  course: {
    _id: "/Api/courses",
    AddCourse: "/add/course",
    updateCourse: "/update/course",
    deleteCourse: "/delete/course",
    AddCourseImg: "/Add/images/to/course",
    deleteCourseImg: "/delete/images/to/course",
    searchCourseByStu: "/search/for/courses/by/student",
    searchCourseByInstructor: "/search/for/courses/by/instructor",
    searchCourseByAdmin: "/search/for/courses/by/Admin",
    GetsingleInfoByAdmin: "/Get/single/course/info/by/Admin",
    GetsingleInfoByInstructor: "/Get/single/course/info/by/instructor",
    GetsingleInfoByStu: "/Get/single/course/info/by/student",
  },
  studentRegister: {
    _id: "/Api/students/registers",
    addCourse: "/add/Course/to/register",
    deleteCourse: "/delete/Course/from/register",
    GetRegisterInfoByStudent: "/get/Register/info/by/student",
    GetRegisterInfoByAdmin: "/get/Register/info/by/Admin",
    searchRegisterByAdmin: "/search/about/courses/registered",
    searchRegisterByInstructor: "/information/about/single/course",
  },
  studentGrades: {
    _id: "/Api/students/Grades",
    AddGradeByAdmin: "/add/grade/by/admin",
    AddGradeByInstructor: "/add/grade/by/instructor",
    updateGradeByAdmin: "/update/grade/by/admin",
    updateGradeByInstructor: "/update/grade/by/instructor",
    deleteGradeByAdmin: "/delete/grade/by/admin",
    deleteGradeByInstructor: "/delete/grade/by/instructor",
    studentsGradesSearchByAdmin: "/search/by/admin",
    studentsGradesSearchByInstructor: "/search/by/instructor",
    GetSingleGradeAboutUserByAdmin: "/Get/Single/grade/about/student/by/admin",
    GetSingleGradeAboutUserByInstructor:
      "/Get/Single/grade/about/student/by/instructor",
    NewspaperBystudent: "Get/Newspaper/By/student",
    NewspaperByAdmin: "Get/Newspaper/By/Admin",
    GetMainsemsterGrade: "Get/Main/semster/Grade/for/student",
  },
  semster: {
    _id: "/Api/semsters",
    addsemster: "/add/semster",
    updatesemster: "/update/semster",
    deletesemster: "/delete/semster",
    searchsemster: "/search/semster",
    MainSemsterInfoBystudent: "/get/main/semster/info/by/student",
    MainSemsterInfoByAdmin: "/get/main/semster/info/by/admin",
    MainSemsterInfoByInstructor: "/get/main/semster/info/by/instructor",
  },
  setting: {
    _id: "/Api/admin/setting",
    updateSetting: "/update",
    deleteSetting: "/delete",
    ViewSetting: "/ViewSetting",
  },
  Training: {
    _id: "/Api/trainings",
    AddTraining: "/add/training",
    updateTraining: "/update/training",
    deleteTraining: "/delete/training",
    AddImages: "/Add/images/to/training",
    deleteImages: "/delete/images/from/training",
    singleTraininginfoByAdmin: "/get/single/training/info/by/admin",
    singleTraininginfoByinstructor:
      "/get/single/training/info/info/by/instructor",
    singleTraininginfoBystudent: "/get/single/training/info/info/by/student",
    allTrainingByAdmin: "/get/all/trainings/info/by/admin",
    allTrainingBystudent: "/get/all/trainings/info/by/student",
    allTrainingByinstructor: "/get/all/trainings/info/by/instructor",
  },
  RegisterTraining: {
    _id: "/Api/Trainings/Registers",
    addTraining: "/add/training/to/register",
    deleteTraining: "/delete/training/from/register",
    getTrainingRegisterdInfoTostu: "/get/trainings/registerd/info/to/student",
    searchTrainingsRegisterdByAdmin: "/search/for/trainings/registerd/by/admin",
    searchTrainingsRegisterdByInstructor:
      "/search/for/trainings/registerd/by/instructor",
    searchTrainingsRegisterdBystudent:
      "/search/for/training/registerd/by/student",
  },
  TrainingResult: {
    _id: "/Api/Trainings/Results",
    uploadByAdmin: "/upload/result/by/admin",
    uploadByInstructor: "/upload/result/by/instructor",
    updateByAdmin: "/update/result/by/Admin",
    updateByInstructor: "/update/result/by/instructor",
    deleteByAdmin: "/delete/results/by/admin",
    deleteByInstructor: "/delete/result/by/instructor",
    getSingleTrainingResultByAdmin: "/get/single/training/result/by/admin",
    getSingleTrainingResultByStudent: "/get/single/training/result/by/student",
    getSingleTrainingResultByInstructor:
      "/get/single/training/result/by/instructor",
    SearchTrainingResultByAdmin: "/search/trainings/result/by/admin",
    SearchTrainingResultByStudent: "/search/trainings/result/by/student",
    SearchTrainingResultByAdminByInstructor:
      "/search/trainings/result/by/instructor",
  },
};
